name: "Push to another git repo"
description: "This action pushes to another git repository"
inputs:
  vsce-token:
   description: "Personal access token for publishing the extension"
   required: true
runs:
  using: docker
  image: Dockerfile
  args: 
  - ${{ inputs.vsce-token }}