name: Publish extension

on:
  release:
    types: [ published ]

  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    name: "Publish extension"
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: "Push"
        uses: ./actions/publish-extension
        id: "publish-extension"
        with:
         vsce-token: ${{ secrets.VSCE_TOKEN }}
         