name: Sync with azure devops

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    name: "Sync with azure devops"
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: "Push"
        uses: ./actions/push-to-other-repo
        id: "push-to-other-repo"
        with:
          repo-url: "https://markostheocharis2009:${{ secrets.AZURE_PASSWORD }}@dev.azure.com/markostheocharis2009/VSCode%20color%20picker/_git/vscode-color-picker"